SEITopic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

#Section for Images.
if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.STATIC_URL+'admin/css/',
        document_root=settings.STATIC_ROOT)
        

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('tshirts/', views.tshirts_index, name='tshirts_index'),
    path('tshirts/<int:tshirt_id>/', views.tshirts_detail, name='tshirts_detail'),
    path('tshirts/<int:tshirt_id>/add_tshirt/', views.add_tshirt, name = 'add_tshirt'),
    path('tshirts/<int:tshirt_id>/add_review/', views.add_review, name='add_review'),
    path('tshirts/<int:tshirt_id>/remove_review/<int:review_id>/', views.remove_review, name='remove_review'),
    path('myimages/',views.myimages,name='myimages'),
    path('cart/', views.show_cart, name='show_cart'),
    path('cart/complete/', views.complete_order, name='complete_order'),
    path('cart/updatequantity/<int:order_details_id>/', views.update_quantity, name='update_quantity'),
    path('cart/removeitem/<int:order_details_id>/', views.remove_item, name='remove_item'),
    path('orderhistory/', views.show_orders, name='show_orders'),
    path('orderhistory/cancelorder/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('orderhistory/<int:order_id>/', views.order_detail, name='order_detail')
]

main_app/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Tshirt(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    image_url = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tshirts_detail', kwargs={'tshirt_id': self.id})
        
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=2)
    zipcode = models.IntegerField()
    
    def item_in_cart(self):
        if self.order_set.filter(complete=False).count():
            cart = self.order_set.get(complete=False)
            return cart.orderdetail_set.all().count()
        return False

class Order(models.Model):
    total_cost= models.DecimalField(max_digits=5, decimal_places=2, default=0)
    date = models.DateField()
    complete = models.BooleanField(default=False)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    tshirts = models.ManyToManyField(Tshirt, through='OrderDetail')


class OrderDetail(models.Model):
    quantity = models.IntegerField(default=1)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    tshirt = models.ForeignKey(Tshirt, on_delete=models.CASCADE)

class Review(models.Model):
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    review_text = models.TextField(max_length=300)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tshirt = models.ForeignKey(Tshirt, on_delete=models.CASCADE)

main_app/forms.py
from django.forms import ModelForm
from .models import OrderDetail, Profile, Review

class ProfileForm(ModelForm):
  class Meta:
    model = Profile
    fields = ['street_address', 'city', 'state', 'zipcode']

class OrderDetailForm(ModelForm):
  class Meta:
    model = OrderDetail
    fields=['quantity']

class ReviewForm(ModelForm):
  class Meta:
    model = Review
    fields = ['rating', 'review_text']

main_app/views.py
import os 
import json
import profile
from django.http import HttpResponse
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .models import Tshirt, Order, OrderDetail, Review
from .forms import ProfileForm, OrderDetailForm, ReviewForm
from datetime import date
# Create your views here.
def home(request):
  return render(request, 'tshirts/home.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    profile_form = ProfileForm(request.POST)
    if form.is_valid() and profile_form.is_valid():
      # This will add the user to the database
      user = form.save()
      profile = profile_form.save(commit=False)
      profile.user = user
      profile.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('tshirts_index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  profile_form = ProfileForm()
  context = {'form': form, 'profile_form': profile_form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def tshirts_index(request):
  tshirts = Tshirt.objects.all()
  return render(request, 'tshirts/index.html', {'tshirts': tshirts})

def tshirts_detail(request, tshirt_id):
  tshirt = Tshirt.objects.get(id=tshirt_id)
  reviews = tshirt.review_set.all()
  return render(request, 'tshirts/detail.html', {'tshirt': tshirt, 'reviews': reviews})

@login_required
def add_tshirt(request, tshirt_id):
  tshirt = Tshirt.objects.get(id=tshirt_id)
  #check if user already has cart-type order
  if request.user.profile.order_set.filter(complete=False).count():
    #grab cart order
    order = request.user.profile.order_set.get(complete=False)
    order_form = OrderDetailForm(request.POST)
    if order_form.is_valid():
      #check if user already has this item in their cart
      if OrderDetail.objects.filter(order=order, tshirt=tshirt).count():
        order_details = OrderDetail.objects.get(order=order, tshirt=tshirt)
        #update quantity on item already in cart
        order_details.quantity += order_form.save(commit=False).quantity
        order_details.save()
        #update total cost
        order.total_cost += order_form.save(commit=False).quantity*tshirt.price
        order.save()
        return redirect('show_cart')
      # create item in cart
      order_details = order_form.save(commit=False)
      #assign appropriate order model and shirt to details
      order_details.order = order
      order_details.tshirt = tshirt
      order_details.save()
      #update total cost
      order.total_cost += order_details.quantity*tshirt.price
      order.save()
      return redirect('show_cart')
  #create cart order if one doesn't exist
  order = Order.objects.create(date = date.today(), user= request.user.profile)
  order_form = OrderDetailForm(request.POST)
  if order_form.is_valid():
    # create item in cart
    order_details = order_form.save(commit=False)
    #assign appropriate order model and shirt to details
    order_details.order = order
    order_details.tshirt = tshirt
    order_details.save()
    #update total cost
    order.total_cost += order_details.quantity*tshirt.price
    order.save()
    return redirect('show_cart')
  #if all checks fail keep them on tshirt page
  return redirect('tshirts_detail', tshirt_id = tshirt_id)

@login_required    
def show_cart(request):
  user = request.user
  if user.profile.order_set.filter(complete=False).count():
    order = request.user.profile.order_set.get(complete=False)
    order_details = OrderDetail.objects.filter(order=order)
    return render(request, 'tshirts/cart.html', {'order': order, 'order_details': order_details})
  order = Order.objects.create(date = date.today(), user= request.user.profile)
  order_details = OrderDetail.objects.filter(order=order)
  return render(request, 'tshirts/cart.html', {'order': order, 'order_details': order_details})

@login_required
def complete_order(request):
  order = request.user.profile.order_set.get(complete=False)
  order.complete = True
  order.save()
  return redirect('show_orders')

@login_required
def show_orders(request):
  user = request.user
  orders = user.profile.order_set.filter(complete=True)
  return render(request, 'tshirts/orderhistory.html', {'user': user, 'orders': orders })

@login_required
def update_quantity(request, order_details_id):
  order_details = OrderDetail.objects.get(id=order_details_id)
  if order_details.order.user.user == request.user:
    update_form = OrderDetailForm(request.POST)
    if update_form.is_valid():
      order_details.order.total_cost += order_details.tshirt.price*(update_form.save(commit=False).quantity - order_details.quantity)
      order_details.order.save()
      order_details.quantity = update_form.save(commit=False).quantity
      order_details.save()
      return redirect('show_cart')
  return redirect('show_cart')

@login_required
def remove_item(request, order_details_id):
  order_details = OrderDetail.objects.get(id=order_details_id)
  if order_details.order.user.user == request.user:
    order_details.order.total_cost -= order_details.quantity*order_details.tshirt.price
    order_details.order.save()
    order_details.delete()
    return redirect('show_cart')
  return redirect('show_cart')

@login_required
def cancel_order(request, order_id):
  order = Order.objects.get(id=order_id)
  order.delete()
  return redirect('show_orders')

@login_required
def order_detail(request, order_id):
  order = Order.objects.get(id=order_id)
  if order.user.user == request.user:
    order_details = OrderDetail.objects.filter(order = order)
    return render(request, 'tshirts/orderdetail.html', {'order': order, 'order_details': order_details})
  return redirect('show_orders')

@login_required
def add_review(request, tshirt_id):
  tshirt = Tshirt.objects.get(id=tshirt_id)
  review = ReviewForm(request.POST).save(commit=False)
  review.tshirt = tshirt
  review.user = request.user
  review.save()
  return redirect('tshirts_detail', tshirt_id = tshirt_id)

@login_required
def remove_review(request, tshirt_id, review_id):
  review = Review.objects.get(id=review_id)
  if review.user == request.user:
    review.delete()
    return redirect('tshirts_detail', tshirt_id = tshirt_id)
  return redirect('tshirts_detail', tshirt_id = tshirt_id)

def myimages(request):
  image_path = os.path.dirname(os.path.realpath(__file__))
  images = os.listdir(image_path+"/static/images/logos")
  json_string = json.dumps(images)
  return HttpResponse(json_string)

main_app/templates/tshirts/cart.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic Shopping Cart</title>
{% endblock %}

{% block content%}
<h1>Shopping Cart</h1>
<hr>
{% if order_details.count %}
<div class="container" id="details-container">
            <div class="card center" style= "width:700px;">
                <div class="card-body" id="orders-card">
                    {% for tshirt in order_details %}
                    <div class="row">
                    <div class="flex-row">
                        <div class="cart-items">
                            <div class="col">
                            <p class="card-text cart-spacing item-name">{{ tshirt.tshirt.name }}</p>
                            </div>
                            <div class="quantity col">
                            <p class="card-text cart-spacing">Quantity: {{ tshirt.quantity }}</p>
                            <div >
                                <div>
                                <form action="{% url 'update_quantity' tshirt.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="number" name="quantity" value="{{ tshirt.quantity }}" required class="quantity-input">
                                    <input type="submit" class="btn btn-sm btn-primary btn-style-1" value="UPDATE" id="update-btn">
                                </form>
                                </div>
                            </div>
                        </div>
                        <div class="col" id="price-remove">
                            <p class="card-text cart-spacing">${{ tshirt.tshirt.price }} each</p>
                            <a href="{% url 'remove_item' tshirt.id %}" class="btn btn-sm btn-danger btn-style-2" id="remove-btn">REMOVE ITEM</a>
                        </div>
                        </div>
                    </div>
                </div>
                <hr>
                    {% endfor %}
                    <h5 class="total-container">Total: ${{ order.total_cost }}</h5>
                    <hr>
                    <h4>Shipping Address</h4>
                    <p>Street Address: {{ order.user.street_address }}</p>
                    <p>City: {{ order.user.city }}</p>
                    <p>State: {{ order.user.state }}</p>
                    <p>Zipcode: {{ order.user.zipcode }}</p>
                    <hr>
                    
                    <form action="{% url 'complete_order' %}" method="POST">
                        {% csrf_token %}
                        <p class="total-container"><button class="btn btn-primary btn-style-1" type="submit">COMPLETE ORDER</button></p>    
                    </form>
                    <p class="total-container"><a href="{% url 'tshirts_index' %}" class="btn btn-primary btn-style-1" >RETURN TO T SHIRTS</a></p>
                </div>
            </div>
        </div>
        
        {% else %}
        <h4 class="center display-message">There is nothing in your cart.</h4>
        {% endif %}
{% endblock %}

main_app/templates/tshirts/checkout.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic Checkout</title>
{% endblock %}

{% block content%}
<h1>Checkout Landing Page</h1>

{% endblock %}

main_app/templates/tshirts/detail.html
{% extends 'base.html' %}
{% block title %}
<title>{{ tshirt.name }} : {{ tshirt.description }}</title>
{% endblock%}


{% block content%}
<h1>Details</h1>
<hr>

<div class="container" id="details-container">
            <div class="card center overflow-hidden" style= "width:500px";>
                <div class="card-body">
                    <div class="center-column">
                    <h5 class="card-title">{{ tshirt.name }}</h5>
                    
                    <div class="tshirt-img center">
                    <img src="{{ tshirt.image_url }}" alt="{{ tshirt.name }} : {{ tshirt.description }}" style="height: 230px">
                    </div>
                    </div>
                    <p class="card-text shirt-description">{{ tshirt.description }}</p>
                    <p class="card-text shirt-price">${{ tshirt.price }}</p>
                    <form action="{% url 'add_tshirt' tshirt.id %}" method="POST">
                        {% csrf_token %}
                        <div>
                        <label for="id_quantity">Quantity:</label>
                        <input type="number" name="quantity" value="1" required class="quantity-input">
                        </div>
                        <br>
                        <div class="reviews-remove">
                        <input type="submit" class="btn btn-primary btn-style-1" value="ADD TO CART">
                    </div>
                    </form>
                    <hr>
                    <div class="reviews-remove">
                    <p><a href="{% url 'tshirts_index' %}" class="btn btn-primary btn-style-1">RETURN TO T SHIRTS</a></p>
                    </div>
                </div>
                <div>
                    <hr>
                    <h4>Add a Review</h4>
                    <br>
                    <form class="" action="{% url 'add_review' tshirt.id %}" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                        <label class="form-label" for="">Rating: </label>
                        <input class="form-control" type="number" name="rating" min="1" max="5"required>
                        </div>
                        <div class="mb-3">
                        <textarea class="form-control" name="review_text" placeholder="Write your review here..." required></textarea>
                        <br>
                        <div class="reviews-remove">
                        <input type="submit" class="btn btn-primary btn-style-1" value="ADD REVIEW">
                        </div>
                    </form>
                    <hr>
                </div>
                <br>
                <h6 id="reviews-label">Reviews:</h6>
                <hr>
                <div>
                    {% if reviews.count %}
                    {% for review in reviews %}
                    <div class="user-rating">
                    <p class="review-user">{{ review.user.username }}</p>
                    <p class="review-rating">Rating: {{review.rating}}</p>
                    </div>
                    <p class="review-content">{{ review.review_text }}</p>
                    {% if review.user == request.user %}
                    <div class="reviews-remove">
                    <a href="{% url 'remove_review' tshirt.id review.id%}" class="btn btn-sm btn-danger btn-style-2" id="delete-btn">DELETE</a>
                    </div>
                    <hr>
                    {% endif %}
                    {% endfor %}
                    {% else %}
                    <p>No reviews yet</p>
                    {% endif %}
                </div>
            </div>
        </div>
    

{% endblock %}

main_app/templates/tshirts/home.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic HELLO!</title>

{% endblock %}




{% block content%}
<h1>Welcome to SEITopic</h1>
<a class="btn btn-primary btn-style-1" href="{% url 'tshirts_index' %}">START SHOPPING</a>
<HR>
    SEITopic is powered by:

    <div>
        <span id="logoRow"></span>
    </div>
{% endblock %}

main_app/templates/tshirts/index.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic - Make your Selections!</title>
{% endblock %}

{% block content%}

<h1>Tshirts</h1>
<hr>
<div class="container">
    <div class="row clearfix">
        {% for tshirt in tshirts %}
        <div class="col">
        <div class="card">
            <div class="card-body center-column">
                <h6 class="card-title">{{ tshirt.name }}</h6>
                <div class="shirt-container">
                    <img src="{{ tshirt.image_url }}" alt="" style="height:140px;">
                </div>
                <p class="card-text shirt-price">${{ tshirt.price }}</p>
                <a href="{% url 'tshirts_detail' tshirt.id %}" class="btn btn-primary btn-style-1">DETAILS</a>
            </div>
        </div>
    </div>
        {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

main_app/templates/tshirts/newPage.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic New Page Template</title>
{% endblock %}

{% block content%}
<h1>Checkout Landing Page</h1>

{% endblock %}

main_app/templates/tshirts/orderdetail.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic Order Detail</title>
{% endblock %}

{% block content%}
<h1>Order #{{ order.id }} </h1>
<hr>
<div class="container" id="details-container">
            <div class="card center" style= "width:700px;">
                <div class="card-body" id="orders-card">
                    {% for tshirt in order_details %}                  
                    <div class="row">
                    <div class="flex-row">
                        <div class="cart-items">
                            <div class="col">
                            <p class="card-text cart-spacing item-name">{{ tshirt.tshirt.name }}</p>
                            </div>  
                            <div class="col">
                            <p class="card-text cart-spacing">Quantity: {{ tshirt.quantity }}</p>
                            </div>
                            <div class="col" id="price-remove">
                            <p class="card-text cart-spacing">${{ tshirt.tshirt.price }} each</p>
                            </div>
                        </div>
                    </div>
                </div>
                    <hr>
                    {% endfor %}
                    <h5 class="total-container">Total: ${{ order.total_cost }}</h5>
                    <hr>
                    <h4>Shipping Address</h4>
                    <p>Street Address: {{ order.user.street_address }}</p>
                    <p>City: {{ order.user.city }}</p>
                    <p>State: {{ order.user.state }}</p>
                    <p>Zipcode: {{ order.user.zipcode }}</p>
                    <p class="total-container"><a href="{% url 'show_orders' %}" class="btn btn-style-1 btn-primary">RETURN TO ORDER HISTORY</a></p>
                </div>
            </div>
        </div>
{% endblock %}

main_app/templates/tshirts/orderhistory.html
{% extends 'base.html' %}

{% block title %}
<title>SEITopic Order History</title>
{% endblock %}

{% block content%}
<h1>Order History for <span class="username">{{ user.username }}</span></h1>

<hr>
{% if orders.count %}
<div class="container center">
    <div id="orders-container" style="width:500px;" class="card">
        <div class="card-body">
        {% for order in orders %}
        <div class="row">
        <div class="flexrow-spc-btwn">
          <div class="col">  
        <h5>Order #: {{ order.id }}</h5>
        </div>
        <div class="col" id="review-cancel">
        <a class="btn btn-primary btn-style-1 history-btn" href="{% url 'order_detail' order.id %}">REVIEW ORDER</a>

        <a class="btn btn-danger btn-style-2 history-btn"  href="{% url 'cancel_order' order.id %}">CANCEL ORDER</a>
        </div>
        </div>
    </div>
        <hr>
        {% endfor %}
        </div>
    </div>
</div>
{% else %}
<h4 class="center display-message">No Orders Yet</h4>
{% endif %}


{% endblock %}